### ISSUE TITLE
Research best way to package and ship php-cs-fixer rules

### ISSUE THREAD

**Issue by simensen** [dflydev/dflydev-php-coding-standards#1]
Ideally, I'd like to be able to require a package with composer and be able to do something like `@dflydev` as a ruleset. However, my little research shows it may be impossible.

The best example I've seen so far is here:

* https://github.com/mollie/php-coding-standards

I'd like to know how you can use Mollie's coding standards using this format:

```php
$rules = [
    '@PER' => true,
    '@Symfony' => true,
    // ...
];


return (new Config())
    ->setFinder($finder)
    ->setRules($rules) // ...
    ->setRiskyAllowed(true)
    ->setUsingCache(true);
```

 * Can we include an array in addition to a class name for `setRules`?
 * Can we call `setRules` multiple times?
 * We'd want to ensure we can easily override the rules inside this package... and that means the order is important.

----

We should use the following as the basis for the ruleset:

```php
<?php

declare(strict_types=1);

use PhpCsFixer\Config;
use PhpCsFixer\Finder;

$rules = [
    '@PER' => true,
    '@Symfony' => true,

    'declare_strict_types' => true,

    // Override @Symfony

    'phpdoc_align' => [
        'align' => 'left',
        'tags' => [
            'method',
            'param',
            'property',
            'property-read',
            'property-write',
            'return',
            'throws',
            'type',
            'var',
        ],
    ],

    'phpdoc_separation' => [
        'groups' => [
            // Defaults
            ['deprecated', 'link', 'see', 'since'],
            ['author', 'copyright', 'license'],
            ['category', 'package', 'subpackage'],
            ['property', 'property-read', 'property-write'],

            // Overrides
            ['template', 'template-covariant', 'template-uses'],

            ['uses'],

            ['phpstan-*'], // This is not available... yet.

            ['phpstan-param', 'phpstan-return'],
        ],
    ],

    'global_namespace_import' => [
        'import_classes' => null,
        'import_constants' => true,
        'import_functions' => true,
    ],
    'no_empty_comment' => false,
    'php_unit_method_casing' => ['case' => 'snake_case'],
    'single_line_throw' => false,
    'yoda_style' => false,

    'phpdoc_to_comment' => [
        'ignored_tags' => [
            'array',
            'var',
            'phpstan-var',
        ],
    ],
];
```

**Comment by zaherg** [comment]
> * Can we include an array in addition to a class name for `setRules`?

the class is returning an array, so if we need to add any new elements we can always use `array_merge`

> * Can we call `setRules` multiple times?

Nope, based on the code here https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/src/Config.php#L261-L270 we can only call it once

> * We'd want to ensure we can easily override the rules inside this package... and that means the order is important.

if I am not mistaken, when using `array_merge` we are going to overwrite any existed element in the array from `Mollie`

I am going to push a simpler solution (which is based on https://github.com/refinery29/php-cs-fixer-config) for you to review.
